force-app/main/default/objects/Prefix__c/Prefix__c.object-meta.xml
<CustomObject>
    <label>Prefix</label>
    <nameField>
        <label>Prefix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prefixes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Prefix__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <referenceTo>UserId__c</referenceTo>
    <relationshipLabel>Prefixes</relationshipLabel>
    <relationshipName>Prefixes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Suffix__c/Suffix__c.object-meta.xml
<CustomObject>
    <label>Suffix</label>
    <nameField>
        <label>Suffix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Suffiexes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Suffix__c/fields/Prefix__c.field-meta.xml
<CustomField>
    <fullName>Prefix__c</fullName>
    <label>Prefix</label>
    <referenceTo>Prefix__c</referenceTo>
    <relationshipLabel>Suffiexes</relationshipLabel>
    <relationshipName>Suffiexes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GetMap.cls
@RestResource(UrlMapping='/GetMap/*')
global class GetMap {
	@HttpPost
    global static Map<String, List<String>> doGet() {
        RestRequest restReq = RestContext.request;
        inputWrapper inputWrpper = (inputWrapper) JSON.deserialize(restReq.requestBody.toString(), inputWrapper.class);
        Map<String, List<String>> markovMap = new Map<String, List<String>>();
        
        List<Prefix__c> prefixes = [
            SELECT Name, (SELECT Name FROM Suffiexes__r)
            FROM Prefix__c
            WHERE UserId__r.Name =: inputWrpper.userId
        ];
        
        for(Prefix__c prefix : prefixes) {
            List<String> suffixes = new List<String>();
            for(Suffix__c suffix : prefix.Suffiexes__r) {
                suffixes.add(suffix.Name);
            }
            markovMap.put(prefix.Name, suffixes);
        }
        
        return markovMap;
    }
    
    private class inputWrapper {
        public String userId;
    }
}